config/routes.rb
Rails.application.routes.draw do
  root to: 'home#show'
  get '/account', to: 'account#show'
  put '/account', to: 'account#edit'
  get '/fitbit/callback', to: 'fitbit#sync'

  resources :users, only: [:new, :create, :update]
  resources :sessions, only: [:create, :destroy]
  resources :workouts, only: [:index, :new, :create] do
    resources :likes, only: [:create]
  end

  namespace :admin do
    resources :teams, only: [:new, :create, :show]
  end

  namespace :team do
    resources :workouts, only: [:index]
  end

end

app/models/activity.rb
class Activity < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :workout

  validates :user, uniqueness: {scope: :workout}
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :users
  before_create :generate_code

  def generate_code
    self.code = '%05d' % rand( 10**5 )
  end
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :team
  has_many :workouts

  has_secure_password
  enum role: [ :user, :admin ]

  def full_name
    "#{first_name} #{last_name}"
  end

  def last_workout
    if workouts.empty?
      return nil
    end
    last = workouts.order(:date).first
    "#{last.distance} mile #{last.activity.name}"
  end
end

app/models/workout.rb
class Workout < ApplicationRecord
  belongs_to :activity
  belongs_to :user
  has_many :likes

  def format_time
    formatted = ""
    if time_elapsed <= 60
      formatted = "#{time_elapsed / 60} hours "
    end
    formatted += "#{time_elapsed % 60} minutes"
  end

  def number_of_likes
    "#{likes.count} likes" unless likes.count == 0
  end
end

app/controllers/account_controller.rb
class AccountController < ApplicationController
  def show
  end

  def edit
    @user = current_user
  end
end

app/controllers/admin/teams_controller.rb
class Admin::TeamsController < ApplicationController
  def new
    @team = Team.new
  end

  def create
    @team = Team.new(team_params)
    if @team.save
      redirect_to admin_team_path(@team)
    else
      render :new
    end
  end

  def show
    @team = Team.find_by_id(params[:id])
  end

  private
    def team_params
      params.require(:team).permit(:name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :current_user
  before_action :require_verified_user

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_verified_user
    session[:user_id] = nil unless current_user
  end
end

app/controllers/fitbit_controller.rb
class FitbitController < ApplicationController
  def sync
    fitbit = FitbitService.new(params[:code])
    fitbit.sync(current_user)
    redirect_to root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    @user = current_user
    if @user && @user.admin?
      render 'admin/teams/index'
    elsif @user
      render 'user/dashboard/show'
    else
      render :dashboard
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    workout = Workout.find_by_id(params[:workout_id])
    Like.create(user: current_user, workout: workout)
    redirect_to team_workouts_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_by_email(params[:session][:email])
    
    if @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      if @user.fitbit_id
        fitbit = FitbitService.new
        fitbit.import_workouts(@user)
      end
      @user.update(last_logged_in: Date.today)
    end

    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/team/workouts_controller.rb
class Team::WorkoutsController < ApplicationController
  def index
    @workouts = Workout.joins(:user).where('users.team_id = ?', current_user.team.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @team = Team.find_by_code(params[:team_code])
    @user = @team.users.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      @user.update(last_logged_in: Date.today)
      redirect_to root_path
    else
      render :new
    end
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to root_path
    else
      render 'account/edit'
    end
  end

  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  def new
    @workout = Workout.new
  end

  def create
    @workout = Workout.new(workout_params)
    if @workout.save
      redirect_to workouts_path
    else
      render :new
    end
  end

  def index
    @workouts = current_user.workouts.where('date > ?', Date.today - 7)
    @total_distance = @workouts.sum(:distance)
  end

  private
    def workout_params
      params.require(:workout)
            .permit(:activity_id, :distance, :calories_burned, :date)
            .merge(time_elapsed: minutes_elapsed)
            .merge(user_id: current_user.id)
    end

    def minutes_elapsed
      time = params[:workout][:time_elapsed]
      time[:hours].to_i * 60 +
      time[:minutes].to_i
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/teams/index.html.erb
<%= link_to 'Create New Team', new_admin_team_path %>

app/views/admin/teams/new.html.erb
<%= form_for [:admin, @team] do |f| %>
  <%= f.text_field 'name', placeholder: 'Team Name' %>
  <%= f.submit 'Create Team' %>
<% end %>

app/views/admin/teams/show.html.erb
<%= @team.name %>
Team Code:
<div class="code">
  <%= @team.code %>
</div>

app/views/home/dashboard.html.erb
<div class='row'>
  <div class='six columns'>
    <%= image_tag 'benefitness_logo.png', class: 'u-max-full-width logo-header' %>
  </div>
</div>

<div class='row'>
  <div class="four columns">
    <%= form_for :session, url: sessions_path do |f| %>
      <%= f.text_field :email, placeholder: 'Email', class:'u-full-width' %>
      <%= f.password_field :password, placeholder: 'Password', class:'u-full-width' %>
      <%= f.submit 'Log in', class: 'u-full-width' %>
      <%= link_to "Create Account", new_user_path, class: 'button button-primary u-full-width' %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Benefitness</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class='container'>
      <%= yield %>
    </div>
    <%= render partial: 'shared/navbar' %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<ul class='navbar'>
  <li class='nav'>
    <%= link_to "Home", root_path, class: 'nav-link' %>
  </li>
  <li class='nav'>
    <%= link_to "Log", new_workout_path, class: 'nav-link' %>
  </li>
  <li class='nav'>
    <%= link_to "Team", team_workouts_path, class: 'nav-link' %>
  </li>
</ul>

app/views/team/workouts/index.html.erb
<div class='row'>
  <div class='six columns'>
    <h3>Team Workouts</h3>
  </div>
</div>
<% @workouts.each do |workout| %>
  <div class="workout">
    <div class='row'>
      <div class='three columns'>
        <%= workout.user.full_name %>
      </div>
    </div>
    <div class='row'>
      <div class='four columns'>
        <%= workout.activity.name %> - 
        <%= workout.distance %> miles
      </div>
    </div>
    <div class='row'>
      <div class='two columns'>
        <%= workout.number_of_likes %>
      </div>
      <div class='two columns'>
        <%= link_to "Like", workout_likes_path(workout), method: :post, class: 'button like' %>
      </div>
    </div>
  </div>
<% end %>

app/views/user/dashboard/show.html.erb
<div class='row'>
  <div class='six columns'>
    <h3>Welcome, <%= current_user.first_name %></h3>
  </div>
</div>
<% if current_user.fitbit_access_token %>
  <div class='row'>
    <div class='three columns'>
      Synced with Fitbit
    </div>
  </div>
<% end %>
<div class='row'>
  <div class='three columns'>
    <strong>Last Workout:</strong>
  </div>
</div>
<div class='row'>
  <div class='three columns'>
    <%= current_user.last_workout %>
  </div>
</div>
<div class='row'>
  <div class='three columns'>
    <%= link_to "Log workout", new_workout_path, class: 'button u-full-width' %>
  </div>
  <div class='three columns'>
    <%= link_to "My Account", account_path, class: 'button u-full-width' %>
  </div>
</div>

<div class='row'>
  <div class='three columns'>
    <%= link_to "My Workouts", workouts_path, class: 'button u-full-width' %>
  </div>
  <div class='three columns'>
    <%= link_to "Team Workouts", team_workouts_path, class: 'button u-full-width' %>
  </div>
</div>

<div class='row'>
  <div class='offset-by-three three columns'>
    <%= link_to "Log out", session_path(current_user), method: :delete, class: 'button u-full-width' %>
  </div>
</div>

app/views/users/new.html.erb
<div class='row'>
  <div class='six columns'>
    <h1>Create Account</h1>
  </div>
</div>

<div class="four columns">
  <%= form_for @user do |f| %>
    <%= f.text_field 'first_name', placeholder: 'First name', class: 'u-full-width' %>
    <%= f.text_field 'last_name', placeholder: 'Last name', class: 'u-full-width' %>
    <%= f.text_field 'email', placeholder: 'Email', class: 'u-full-width' %>
    <%= f.password_field 'password', placeholder: 'Password', class: 'u-full-width' %>
    <%= f.password_field 'password_confirmation', placeholder: 'Confirm Password', class: 'u-full-width' %>
    <%= text_field_tag 'team_code', nil, placeholder: 'Team Code', class: 'u-full-width' %>
    <%= f.submit 'Create', class: 'button-primary' %>
  <% end %>
</div>

app/views/workouts/index.html.erb
<div class='row'>
  <div class='six columns'>
    <h3>My Workouts</h3>
  </div>
</div>

<% @workouts.each do |workout| %>
  <div class="workout">
    <div class='row'>
      <div class='four columns'>
        <%= workout.activity.name %> - 
        <%= workout.distance %> miles
      </div>
    </div>
    <div class='row'>
      <div class="three columns">
        <%= workout.format_time %>
      </div>
      <div class="three columns">
        <%= workout.calories_burned %> calories burned
      </div>
    </div>
  </div>
<% end %>

<br>
<div class="summary">
  <div class='row'>
    <div class='six columns'>
      <h5>Weekly Summary</h5>
    </div>
  </div>
  <div class='row'>
    <div class='two columns'>
      <%= @total_distance %> miles
    </div>
  </div>
</div>

app/views/workouts/new.html.erb
<div class='row'>
  <div class='six columns'>
    <h3>Log Workout</h3>
  </div>
</div>

<%= form_for @workout do |f| %>
  <%= f.label :activity %>
  <%= collection_select(:workout, :activity_id, Activity.all, :id, :name, prompt: true) %> 
  <%= f.label :date %>
  <%= f.text_field :date %>
  <%= f.label :distance %>
  <%= f.text_field :distance %> miles
  <%= f.label :duration %>
  <%= f.fields_for :time_elapsed do |time_fields| %>
    <%= time_fields.text_field :hours %> hours
    <%= time_fields.text_field :minutes %> minutes
  <% end %>
  <%= f.label :calories_burned %>
  <%= f.text_field :calories_burned %>
  <%= f.submit 'Add workout', class: 'button-primary' %>
<% end %>